openapi: 3.0.0
info:
  title: IMBAG API - van de LVBAG
  description: '"Dit is de BAG API van de landelijke voorziening BAG (LVBAG) voor
    het informatiemodel IMBAG 2.0 en conform de API strategie 1.1 specificatie in
    OAS3. Deze is vooral gericht op individuele bevragingen (op basis van de identificerende
    gegevens van een object).  <br/><br/> <font color=''red''>**LET OP: Deze specificatie
    is een \"work in progress\"**, oftewel niet definitief.</font><br/><br/> Meer
    informatie over BAG 2.0 is te vinden op: [Catalogus BAG 2.0](https://www.geobasisregistraties.nl/basisregistraties/adressen-en-gebouwen)
    <br/> Meer informatie over Nederlandse API strategie is te vinden op: [API-Strategie](https://docs.geostandaarden.nl/api/API-Strategie)
    - deze API volgt versie 1.1 van 20190213.  <br/> Meer informatie over OAS3 specificatie
    is te vinden op: [OAS](https://www.forumstandaardisatie.nl/standaard/openapi-specification)   <br/>
    Het standaard mediatype HAL (`application/hal+json`) wordt gebruikt. Dit is een
    mediatype voor het weergeven van resources en hun relaties via hyperlinks. <br/>
    <br/> Voor vragen, neem contact op met de BAG beheerder o.v.v. BAG API 2.0. We
    zijn aan het kijken naar een geschikt medium hiervoor, mede ook om de API iteratief
    te kunnen opstellen of doorontwikkelen samen met de community. Als de API iets
    (nog) niet kan, wat u wel graag wilt, neem dan contact op.  <br/> <br/> Een API-key
    kan  verkregen worden door een e-mail te sturen naar: zie onderstaande contactgegevens
    <font color=''blue''>send e-mail</font>." '
  termsOfService: https://zakelijk.kadaster.nl/algemene-voorwaarden
  contact:
    name: Kadaster - Beheerder Landelijke Voorziening BAG
    url: https://zakelijk.kadaster.nl/bag
    email: bag@kadaster.nl
  license:
    name: European Union Public License, version 1.2 (EUPL-1.2)
    url: https://eupl.eu/1.2/nl/
  version: "0.1"
servers:
- url: https://api.test.kadaster.nl/lvbag/api/individuelebevragingen/v1
  description: LVBAG - TEST
- url: https://api.kadaster.nl/lvbag/api/individuelebevragingen/v1
  description: LVBAG - PRODUCTIE
security:
- apiKeyBAG: []
tags:
- name: Algemene informatie
  description: Het endpoint voor algemene informatie levert informatie op van de API.
paths:
  /info:
    get:
      tags:
      - Algemene informatie
      summary: Algemene info van de API
      operationId: getInfo
      responses:
        200:
          description: Bevraging getInfo geslaagd
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/API-info'
        default:
          description: Onverwacht probleem
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - apiKeyBAG: []
components:
  schemas:
    API-info:
      title: API-info
      type: object
      properties:
        api-name:
          type: string
          description: De naam van de API.
        api-version:
          type: string
          description: Versie van de API.
        api-description:
          type: string
          description: Omschrijving van de API.
        informationmodel:
          type: string
          description: Naam van het informatiemodel dat als basis is genomen voor
            deze API.
          example: IMBAGLV
        informationmodel-version:
          type: string
          description: Versie van het logische informatiemodel dat als basis is genomen
            voor deze API.
          example: v20190601
        informationmodel-location:
          type: string
          description: Locatie (URI) van het logische informatiemodel die als basis
            is genomen voor deze API.
          format: URI
    Error:
      title: Error
      required:
      - detail
      - instance
      - status
      - title
      - type
      type: object
      properties:
        detail:
          type: string
          description: Een gedetailleerde beschrijving van de HTTP status code.
          example: Je hebt geen rechten om deze URL te benaderen. Bij 403 Forbidden.
        instance:
          type: string
          description: URI van de aanroep die fout heeft veroorzaakt.
          format: uri
        status:
          type: integer
          description: De HTTP status code.
        title:
          type: string
          description: De titel behorende bij de HTTP status code.
          example: OK, Forbidden, Unauthorized, Not Found etc.
        type:
          type: string
          description: URI naar een pagina met meer informatie over deze foutmelding
            voor de ontwikkelaar.
          format: uri
          example: about:blank
          default: about:blank
        code:
          minLength: 1
          type: string
          description: Systeem code die het type fout aangeeft.
  securitySchemes:
    apiKeyBAG:
      type: apiKey
      description: |
        De API-key die je hebt gekregen dient bij elke request naar deze via de `X-Api-Key` request header meegestuurd te worden. Indien deze niet juist wordt meegestuurd, of het een ongeldige key betreft, zul je de foutmelding `403 Forbidden` terugkrijgen.
      name: X-Api-Key
      in: header
