page:
  description: Pagina nummer
  name: page
  in: query
  required: false
  schema:
    type: integer
    minimum: 1
    default: 1

pageSize:
  description: Aantal resultaten per pagina
  name: pageSize
  in: query
  required: false
  schema:
    type: integer
    minimum: 10
    maximum: 100
    default: '20'

expand:
  in: query
  name: expand
  description: 'Hier kan aangegeven worden welke gerelateerde resources meegeladen moeten worden. Resources en velden van resources die gewenst zijn kunnen in de expand parameter kommagescheiden worden opgegeven. Specifieke velden van resource kunnen worden opgegeven door het opgeven van de resource-naam gevolgd door de veldnaam, met daartussen een punt.'
  required: false
  schema:
    type: string

contentType:
  name: Content-Type
  in: header
  required: false
  description: Media type van het request.
  schema:
    type: string

contentCrs:
  name: Content-Crs
  in: header
  required: false
  description: CRS van de meegegeven geometrie.
  schema:
    type: string
    enum:
#      - epsg:4326 wordt nog niet ondersteund
#      - epsg:3857 wordt nog niet ondersteund
#      - epsg:4258 wordt nog niet ondersteund
      - epsg:28992
# Default weglaten i.v.m. breaking change als de default anders wordt bij het uitbreiden van CRS ondersteuning. 
# Zodra WGS84 ondersteund wordt, moet dat de default zijn.
#    default: epsg:28992 

acceptCrs:
  name: Accept-Crs
  in: header
  required: false
  description: Gewenste CRS van de coördinaten in de response.
  schema:
    description: 'CRS van de coördinaten in de response.'
    type: string
    enum:
#      - epsg:4326 wordt nog niet ondersteund
#      - epsg:3857 wordt nog niet ondersteund
#      - epsg:4258 wordt nog niet ondersteund
      - epsg:28992 
# Default weglaten i.v.m. breaking change als de default anders wordt bij het uitbreiden van CRS ondersteuning. 
# Zodra WGS84 ondersteund wordt, moet dat de default zijn.
#    default: epsg:28992 
